apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: etl
  name: etl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etl
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: etl
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: operational_analytics
            - name: DB_PASS
              value: hunter2
            - name: DB_USER
              value: user
            - name: LOG_PATH
              value: syslog
          image: ethanrusz/tmc-etl:latest
          name: etl
          resources: {}
          stdin: true
      hostname: etl
      restartPolicy: Always
status: {}
